version: '3.8'

services:

  mysql:

    image: mysql:8.0

    container_name: mysql_janken

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: janken

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:

    image: phpmyadmin/phpmyadmin

    container_name: phpmyadmin_janken

    restart: always

    ports:
      - "8081:80"

    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 1234

    depends_on:
      - mysql

  springboot:

    build: .

    container_name: spring_janken

    restart: always

    ports:
      - "8080:8080"

    depends_on:
      - mysql

volumes:
  mysql_data: